timeout: 1800s

options:
  machineType: 'N1_HIGHCPU_8'

steps:

  # npmInstall
  - name: 'gcr.io/cloud-builders/npm:node-14.10.0'
    id: npmInstall
    volumes:
    - name: 'node-modules'
      path: '/workspace/client/node_modules'
    args: ['install']
    dir: 'client/'
    waitFor: ['-']

  # Build client image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build client image'
    volumes:
    - name: 'node-modules'
      path: '/workspace/client/node_modules'
    args:
      - 'build'
      - '--file=Dockerfile'
      - '--tag=eu.gcr.io/${_PROJECT_ID}/${_FRONT_REPO_NAME}:$COMMIT_SHA'
      - '.'
    dir: 'client/'

  # Create custom image tag and write to file /workspace/_TAG
  - name: 'ubuntu'
    id: 'Prepare tag name'
    args: ['bash', '-c', "echo `echo $TAG_NAME$BRANCH_NAME | sed 's,/,-,g' | awk '{print tolower($0)}'`-$(date -u +%Y%m%dT%H%M)-$SHORT_SHA > _TAG; echo $(cat _TAG)"]

  # Tag client image with custom tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Tag client image'
    entrypoint: '/bin/bash'
    args: ['-c', "docker tag eu.gcr.io/${_PROJECT_ID}/${_FRONT_REPO_NAME}:$COMMIT_SHA eu.gcr.io/${_PROJECT_ID}/${_FRONT_REPO_NAME}:$(cat _TAG)"]

  # Fetch Strio OAuth token from Secrets Manager
  - name: gcr.io/cloud-builders/gcloud
    id: 'Fetch Strio OAuth token from Secrets Manager'
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=strio-oauth-token-proximum --format='get(payload.data)' | tr '_-' '/+' | base64 -d > strio-oauth-token.txt" ]

  # Notify Strio about the completed build
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Notify Strio'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TOKEN="$$(<strio-oauth-token.txt)"
        RESULT="$$(curl --request POST \
                     --url https://strio-api.synalabs.cloud/events/external \
                     --header "Authorization: Bearer $$TOKEN" \
                     --header 'Content-Type: application/json' \
                     --data '{
                   "repository": "proximum/vimeet365",
                   "provider": "github",
                   "job_name": "build",
                   "head_sha": "$COMMIT_SHA",
                   "state": "success"
                   }')"
        echo "Strio is notified: $${RESULT}"

substitutions:
  _PROJECT_ID: "proximum-vimeet-staging"
  _FRONT_REPO_NAME: "vimeet365_client"

images: [
  'eu.gcr.io/${_PROJECT_ID}/${_FRONT_REPO_NAME}'
]
