flysystem:
    storages:
        companyLogos.storage:
            adapter: 'gcloud'
            options:
                client: 'gcloud_client_service'
                bucket: '%env(resolve:GCS_PUBLIC_BUCKET)%'
                # prefix: ''
        accountAvatar.storage:
            adapter: 'gcloud'
            options:
                client: 'gcloud_client_service'
                bucket: '%env(resolve:GCS_PUBLIC_BUCKET)%'
                # prefix: ''

service:
    gcloud_client_service:
        class: Google\Cloud\Storage\StorageClient
        arguments:
            projectId: '%env(resolve:GCS_PROJECT_ID)%'
