{{- if .Values.persistence.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.existingClaim }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  nfs:
    server: {{ .Values.persistence.nfs.server }}
    path: {{ .Values.persistence.nfs.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.existingClaim }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end -}}
