{{- if .Values.ingress.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  labels:
    {{- include "vimeet365.labels" . | nindent 4 }}
    app: "{{ template "vimeet365.name" . }}"
    chart: "{{ template "vimeet365.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    strategy.spinnaker.io/versioned: 'false'
type: Opaque
stringData:
  auth: |
    {{- range $key, $value := .Values.ingress.basicAuth.users }}
    {{ $key }}:{{ $value }}
    {{- end }}
{{- end }}
