Proximum\Vimeet365\Domain\Entity\Account:
    attributes:
        pagination_items_per_page: 10
        output: 'Proximum\Vimeet365\Application\View\AccountView'
    collectionOperations:
        get: ~
        post:
            input: 'Proximum\Vimeet365\Application\Command\Account\RegistrationCommand'
            messenger: 'input'
    itemOperations:
        get: ~
