Proximum\Vimeet365\Application\View\CountryView:
    collectionOperations:
        get:
            path: "/countries"
    itemOperations:
        get: ~
    properties:
        code: { identifier: true }
