Proximum\Vimeet365\Domain\Entity\Member:
    attributes:
        output: 'Proximum\Vimeet365\Application\View\MemberView'
    collectionOperations:
        get: ~
        post:
            messenger: input
            input: 'Proximum\Vimeet365\Application\Command\Member\JoinCommunityCommand'
            security: 'is_granted("ROLE_USER")'
    itemOperations:
        get: ~
        patch:
            messenger: input
            input: 'Proximum\Vimeet365\Application\Command\Member\SetCommunityTagCommand'
            security: 'is_granted("ROLE_USER") and object.getAccount() == user.getAccount()'
    properties:
        id: { identifier: true }
