parameters:
    supported_languages: [en, fr]
    default_language: en

framework:
    default_locale: '%default_language%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%default_language%'
