elao_enum:
    # Provide the enum classes for which you want to automatically generate & register Doctrine DBAL Types:
    # https://github.com/Elao/PhpEnums#doctrine
    doctrine:
        types:
            card_list_sorting: 'Proximum\Vimeet365\Core\Domain\Entity\Community\Card\Sorting'
            card_list_card_type: 'Proximum\Vimeet365\Core\Domain\Entity\Community\Card\CardType'
            card_list_card_types:
                class: 'Proximum\Vimeet365\Core\Domain\Entity\Community\Card\CardType'
                type: csv_collection
            community_event_type: 'Proximum\Vimeet365\Core\Domain\Entity\Community\Event\EventType'
            community_media_type: 'Proximum\Vimeet365\Core\Domain\Entity\Community\Media\MediaType'
