# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_domain: "%env(SESSION_COOKIE_DOMAIN)%"

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        packages:
            companyLogos:
                base_urls: "%env(CDN_HOST)%/companyLogos"
            accountAvatar:
                base_urls: "%env(CDN_HOST)%/accountAvatar"
            eventPictures:
                base_urls: "%env(CDN_HOST)%/eventPictures"
            mediaVideos:
                base_urls: "%env(CDN_HOST)%/mediaVideos"

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
