security:
    enable_authenticator_manager: true

    encoders:
        Proximum\Vimeet365\Api\Infrastructure\Security\SymfonyUser:
            algorithm: 'auto'

    providers:
        user_provider:
            id: Proximum\Vimeet365\Api\Infrastructure\Security\SymfonyUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            pattern: ^/api/
            json_login:
                check_path: /api/login
            provider: user_provider

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
