services:
    app.alice.property_access.reflection_property_accessor:
        class: Nelmio\Alice\PropertyAccess\ReflectionPropertyAccessor
        public: false
        decorates: nelmio_alice.property_accessor
        decoration_priority: -10
        arguments: ["@app.symfony.property_access.property_accessor"]

    app.symfony.property_access.property_accessor:
        class: Symfony\Component\PropertyAccess\PropertyAccessor
        public: false

    Proximum\Vimeet365\Core\Infrastructure\DataFixtures\EnumProvider:
        autowire: true
        autoconfigure: true

    Proximum\Vimeet365\Core\Infrastructure\DataFixtures\ImmutableDateProvider:
        autowire: true
        autoconfigure: true
