#! /bin/bash

echo "hostname:" `hostname`
echo "date:" `date`
echo "whoami:" `whoami`
echo "debug: $DEBUG"

# Do not stop on errors
set +e
# Verbose command execution
set -x


# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

exec "$@"
