timeout: 1800s

options:
  machineType: 'N1_HIGHCPU_8'

steps:

  # Build SERVER image 
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build API image'
    args:
      - 'build'
      - '--file=Dockerfile'
      - '--tag=eu.gcr.io/${_PROJECT_ID}/${_API_REPO_NAME}:$COMMIT_SHA'
      - '.'
    dir: 'server/'
    waitFor: ['-']

  # Create custom image tag and write to file /workspace/_TAG
  - name: 'ubuntu'
    id: 'Prepare tag name'
    args: ['bash', '-c', "echo `echo $TAG_NAME$BRANCH_NAME | sed 's,/,-,g' | awk '{print tolower($0)}'`-$(date -u +%Y%m%dT%H%M)-$SHORT_SHA > _TAG; echo $(cat _TAG)"]

  # Tag SERVER image with custom tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Tag SERVER image'
    entrypoint: '/bin/bash'
    args: ['-c', "docker tag eu.gcr.io/${_PROJECT_ID}/${_API_REPO_NAME}:$COMMIT_SHA eu.gcr.io/${_PROJECT_ID}/${_API_REPO_NAME}:$(cat _TAG)"]

substitutions:
  _PROJECT_ID: "proximum-vimeet-staging"
  _API_REPO_NAME: "vimeet365_server"

images: [
    'eu.gcr.io/${_PROJECT_ID}/${_API_REPO_NAME}'
]
