Proximum\Vimeet365\Core\Domain\Entity\Account:
    attributes:
        pagination_items_per_page: 10
        output: 'Proximum\Vimeet365\Api\Application\View\AccountView'
    collectionOperations:
        get: ~
        post:
            input: 'Proximum\Vimeet365\Api\Application\Command\Account\RegistrationCommand'
            messenger: "input"
    itemOperations:
        get:
            requirements:
                id: '\d+'
        get_me:
            method: get
            path: /accounts/me.{_format}
            controller: Proximum\Vimeet365\Api\Infrastructure\Controller\AccountController::getMe
            read: false
            security: 'is_granted("ROLE_USER")'
            openapi_context:
                summary: Retrieve the current account
        account_patch_profile:
            method: patch
            path: /accounts/{id}/profile
            controller: Proximum\Vimeet365\Api\Infrastructure\Controller\AccountController::updateProfile
            input: Proximum\Vimeet365\Api\Application\Command\Account\UpdateProfileCommand
            security: 'is_granted("ROLE_USER") and is_granted("OWNER", object)'
        account_post_company:
            method: post
            path: /accounts/{id}/company
            controller: 'Proximum\Vimeet365\Api\Infrastructure\Controller\AccountController::createCompany'
            input: Proximum\Vimeet365\Api\Application\Command\Account\Company\CreateCommand
            security: 'is_granted("ROLE_USER") and is_granted("OWNER", object)'
            openapi_context:
                summary: Create a company
        account_put_company:
            method: put
            path: /accounts/{id}/company
            controller: 'Proximum\Vimeet365\Api\Infrastructure\Controller\AccountController::linkCompany'
            input: Proximum\Vimeet365\Api\Application\Command\Account\Company\LinkCommand
            security: 'is_granted("ROLE_USER") and is_granted("OWNER", object)'
            openapi_context:
                summary: Link an existing company to the account
        account_patch_company:
            method: patch
            path: /accounts/{id}/company
            controller: 'Proximum\Vimeet365\Api\Infrastructure\Controller\AccountController::updateCompany'
            input: Proximum\Vimeet365\Api\Application\Command\Account\Company\UpdateCommand
            security: 'is_granted("ROLE_USER") and is_granted("OWNER", object)'
            openapi_context:
                summary: Update the existing company of the account
        account_validate:
            method: get
            path: /accounts/{id}/validation
            controller: Proximum\Vimeet365\Api\Infrastructure\Controller\AccountController::validate
            security: 'is_granted("ROLE_USER") and is_granted("OWNER", object)'
            openapi_context:
                summary: Validate a user account
        account_check_token:
            method: post
            path: /accounts/{id}/validation
            controller: Proximum\Vimeet365\Api\Infrastructure\Controller\AccountController::checkValidationToken
            input: Proximum\Vimeet365\Api\Application\Command\Account\CheckValidationTokenCommand
            openapi_context:
                summary: Check if the account validation token is valid

        account_post_avatar:
            method: post
            path: /accounts/{id}/avatar
            controller: 'Proximum\Vimeet365\Api\Infrastructure\Controller\AccountController::uploadAvatar'
            security: 'is_granted("ROLE_USER") and is_granted("OWNER", object)'
            deserialize: false
            openapi_context:
                summary: Upload an avatar
                requestBody:
                    content:
                        multipart/form-data:
                            schema:
                                type: object
                                properties:
                                    file:
                                        type: string
                                        format: binary
                                        description: muste be png or jpeg file, with a 1M max size
                            encoding:
                                logo:
                                    # only accept png/jpeg
                                    contentType: image/png, image/jpeg
    properties:
        company:
            subresource:
                resourceClass: 'Proximum\Vimeet365\Core\Domain\Entity\Company'
                collection: false
