Proximum\Vimeet365\Core\Domain\Entity\Community:
    collectionOperations:
        get:
            path: "/communities"
            output: 'Proximum\Vimeet365\Api\Application\View\CommunityListView'
    itemOperations:
        get:
            path: "/communities/{id}"
            requirements: { id: '\d+' }
            output: 'Proximum\Vimeet365\Api\Application\View\CommunityView'
    properties:
        id: { identifier: true }
        nomenclatures:
            subresource:
                resourceClass: 'Proximum\Vimeet365\Core\Domain\Entity\Nomenclature'
                collection: true
        goals:
            subresource:
                resourceClass: 'Proximum\Vimeet365\Core\Domain\Entity\Community\Goal'
                collection: true
        cardLists:
            subresource:
                resourceClass: 'Proximum\Vimeet365\Core\Domain\Entity\Card\CardList'
                collection: true
