Proximum\Vimeet365\Core\Domain\Entity\Community\Goal:
    shortName: CommunityGoal
    attributes:
        output: 'Proximum\Vimeet365\Api\Application\View\Goal\CommunityGoalView'
    collectionOperations:
        get:
            path: "/communityGoals"
    itemOperations:
        get:
            path: "/communityGoals/{id}"
    properties:
        id: { identifier: true }
