Proximum\Vimeet365\Domain\Entity\Company:
    attributes:
        pagination_items_per_page: 10
    collectionOperations:
        get: ~
        post:
            messenger: input
            input: 'Proximum\Vimeet365\Application\Command\Account\Company\CreateCommand'
    itemOperations:
        get: ~
        post_logo:
            method: post
            path: /companies/{id}/logo
            controller: 'Proximum\Vimeet365\Infrastructure\Controller\CompanyController::uploadLogo'
            security: 'is_granted("ROLE_USER") and is_granted("OWNER", object)'
            deserialize: false
            openapi_context:
                summary: Upload a logo
                requestBody:
                    content:
                        multipart/form-data:
                            schema:
                                type: object
                                properties:
                                    logo:
                                        type: string
                                        format: binary
                                        description: muste be png or jpeg file, with a 1M max size
                            encoding:
                                logo:
                                    # only accept png/jpeg
                                    contentType: image/png, image/jpeg
