Proximum\Vimeet365\Api\Application\View\CountryView:
    collectionOperations:
        get:
            path: "/countries"
    itemOperations:
        get:
            path: "/countries/{code}"
    properties:
        code: { identifier: true }
    attributes:
        pagination_enabled: false
