Proximum\Vimeet365\Api\Application\View\HubSpot\CompanyView:
    shortName: Hubspot Company
    collectionOperations:
        get:
            path: "/hubspot/companies"
            openapi_context:
                parameters:
                    - name: domain
                      in: query
                      required: true
                      type: string
                    - name: limit
                      in: query
                      type: int
    itemOperations:
        get:
            path: "/hubspot/companies/{hubspotId}"
    properties:
        hubspotId: { identifier: true }
    attributes:
        pagination_enabled: false
