Proximum\Vimeet365\Core\Domain\Entity\Tag:
    attributes:
        output: Proximum\Vimeet365\Api\Application\View\TagView
    collectionOperations: []
    itemOperations:
        get: ~
    properties:
        id: { identifier: true }
