#! /bin/bash

echo "hostname:" `hostname`
echo "date:" `date`
echo "whoami:" `whoami`
echo "debug: $DEBUG"

# Do not stop on errors
set +e
# Verbose command execution
set -x

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

if [ "$1" = 'apache2-foreground' ] || [ "$1" = 'bin/console' ]; then
    mkdir -p var/cache var/log
    setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var
    setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var
    
	until bin/console doctrine:query:sql "select 1" >/dev/null 2>&1; do
	    (>&2 echo "Waiting for PostgreSQL to be ready...")
		sleep 1
	done

fi

exec "$@"