apiVersion: v1
kind: Service
metadata:
  name: {{ template "vimeet365.fullname" . }}
  labels:
    app: "{{ template "vimeet365.name" . }}"
    tier: server
    chart: "{{ template "vimeet365.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
          {{- if .Values.service.annotations }}
  annotations:
          {{- range $key, $value := .Values.service.annotations }}
          {{ $key }}: {{ $value | quote }}
          {{- end }}
          {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.http)))}}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
  selector:
    app: "{{ template "vimeet365.name" . }}"
    tier: server
