{{- if .Values.persistence.local -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "vimeet365.fullname" . }}-shared-local
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.localHostPath | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "vimeet365.fullname" . }}-shared-local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
{{- end -}}
